/**
 * AI provider definitions.
 *
 * baseUrl: Fixed base URL (null = user must supply via custom URL field)
 * format:  'openai' | 'anthropic' | 'cohere' | 'minimax'
 * authType:'bearer' | 'x-api-key' | 'api-key' | 'none'
 * chatPath: path appended to baseUrl; use {model} placeholder where needed
 * modelsPath: path to list models; null = use staticModels
 * modelsResponseKey: key in JSON response that holds the array (null = root array)
 * modelIdField: field on each model object that holds the usable model ID
 * filterModels: optional fn(modelObj) => boolean
 * extraHeaders: extra request headers
 */
export const PROVIDERS = [
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'openai/gpt-4o-mini',
    keyPlaceholder: 'sk-or-v1-…',
    extraHeaders: { 'HTTP-Referer': 'https://vocabkids.app', 'X-Title': 'VocabKids' },
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    baseUrl: 'https://api.anthropic.com',
    format: 'anthropic',
    authType: 'x-api-key',
    chatPath: '/v1/messages',
    modelsPath: '/v1/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'claude-3-5-haiku-20241022',
    keyPlaceholder: 'sk-ant-…',
    extraHeaders: { 'anthropic-version': '2023-06-01' },
  },
  {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    filterModels: (m) => m.id && (m.id.startsWith('gpt-') || m.id.startsWith('o1') || m.id.startsWith('o3') || m.id.startsWith('o4')),
    defaultModel: 'gpt-4o-mini',
    keyPlaceholder: 'sk-…',
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    baseUrl: null,
    requiresCustomUrl: true,
    urlHint: 'https://{resource}.openai.azure.com/openai',
    format: 'azure',
    authType: 'api-key',
    chatPath: '/deployments/{model}/chat/completions?api-version=2024-10-21',
    modelsPath: '/models?api-version=2024-10-21',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: '',
    keyPlaceholder: 'Azure API key',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    // OpenAI-compatible endpoint (officially supported by Google)
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    filterModels: (m) => m.id && m.id.startsWith('gemini-'),
    defaultModel: 'gemini-2.0-flash',
    keyPlaceholder: 'AIza…',
  },
  {
    id: 'vertex',
    name: 'Google Vertex AI',
    baseUrl: null,
    requiresCustomUrl: true,
    urlHint: 'https://{region}-aiplatform.googleapis.com/v1beta1/projects/{project}/locations/{region}/endpoints/openapi',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    staticModels: ['google/gemini-2.5-flash', 'google/gemini-2.0-flash-001', 'google/gemini-1.5-pro-002', 'google/gemini-1.5-flash-002', 'google/gemma-3-27b-it'],
    defaultModel: 'google/gemini-2.0-flash-001',
    keyPlaceholder: 'gcloud OAuth token (gcloud auth print-access-token)',
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    baseUrl: 'http://localhost:11434',
    requiresCustomUrl: true,
    urlHint: 'http://localhost:11434',
    format: 'openai',
    authType: 'none',
    chatPath: '/v1/chat/completions',
    modelsPath: '/v1/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'llama3.2',
    keyPlaceholder: '(not required)',
  },
  {
    id: 'ollama-cloud',
    name: 'Ollama (Cloud)',
    baseUrl: null,
    requiresCustomUrl: true,
    urlHint: 'https://your-ollama-server.example.com',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/v1/chat/completions',
    modelsPath: '/v1/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: '',
    keyPlaceholder: 'Bearer token (if your server requires auth)',
  },
  {
    id: 'venice',
    name: 'Venice',
    baseUrl: 'https://api.venice.ai/api/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    filterModels: (m) => m.type === 'text' || !m.type,
    defaultModel: 'llama-3.3-70b',
    keyPlaceholder: 'Venice API key',
  },
  {
    id: 'groq',
    name: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'llama-3.1-8b-instant',
    keyPlaceholder: 'gsk_…',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    baseUrl: 'https://api.mistral.ai/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'mistral-small-latest',
    keyPlaceholder: 'Mistral API key',
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'grok-3-mini',
    keyPlaceholder: 'xai-…',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/v1/chat/completions',
    modelsPath: '/v1/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'deepseek-chat',
    keyPlaceholder: 'sk-…',
  },
  {
    id: 'together',
    name: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: null, // response is a root array
    modelIdField: 'id',
    filterModels: (m) => !m.type || m.type === 'chat' || m.type === 'language',
    defaultModel: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
    keyPlaceholder: 'Together API key',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: null, // no documented public endpoint
    staticModels: [
      'accounts/fireworks/models/llama-v3p3-70b-instruct',
      'accounts/fireworks/models/llama-v3p1-8b-instruct',
      'accounts/fireworks/models/mixtral-8x22b-instruct',
      'accounts/fireworks/models/qwen3-30b-a3b',
      'accounts/fireworks/models/deepseek-v3',
      'accounts/fireworks/models/kimi-k2-instruct-0905',
    ],
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    keyPlaceholder: 'fw_…',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/v1/sonar',   // Perplexity's primary chat endpoint
    modelsPath: '/v1/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    staticModels: ['sonar', 'sonar-pro', 'sonar-reasoning', 'sonar-reasoning-pro', 'sonar-deep-research', 'r1-1776'],
    defaultModel: 'sonar',
    keyPlaceholder: 'pplx-…',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    baseUrl: 'https://api.cohere.com',
    format: 'cohere',
    authType: 'bearer',
    chatPath: '/v2/chat',
    modelsPath: '/v2/models',
    modelsResponseKey: 'models',
    modelIdField: 'name',
    filterModels: (m) => !m.endpoints || m.endpoints.includes('chat'),
    defaultModel: 'command-a-03-2025',
    keyPlaceholder: 'Cohere API key',
  },
  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    baseUrl: null,
    requiresCustomUrl: true,
    urlHint: 'https://bedrock-runtime.{region}.amazonaws.com',
    format: 'bedrock', // AWS SigV4 — not supported in browser
    authType: 'none',
    chatPath: '',
    modelsPath: null,
    staticModels: [
      'anthropic.claude-3-5-sonnet-20241022-v2:0',
      'anthropic.claude-3-5-haiku-20241022-v1:0',
      'anthropic.claude-3-opus-20240229-v1:0',
      'amazon.nova-pro-v1:0',
      'amazon.nova-lite-v1:0',
      'meta.llama3-70b-instruct-v1:0',
      'mistral.mistral-large-2402-v1:0',
    ],
    defaultModel: 'anthropic.claude-3-5-haiku-20241022-v1:0',
    keyPlaceholder: '(AWS Bedrock requires server-side auth — not usable from browser)',
    disabled: true,
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseUrl: 'https://api.minimax.chat/v1',
    format: 'minimax',
    authType: 'bearer',
    chatPath: '/text/chatcompletion_v2',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: 'MiniMax-M1',
    keyPlaceholder: 'MiniMax API key',
  },
  {
    id: 'custom',
    name: '⚙️ Custom / Self-hosted',
    baseUrl: null,
    requiresCustomUrl: true,
    urlHint: 'https://your-api-endpoint.com/v1',
    format: 'openai',
    authType: 'bearer',
    chatPath: '/chat/completions',
    modelsPath: '/models',
    modelsResponseKey: 'data',
    modelIdField: 'id',
    defaultModel: '',
    keyPlaceholder: 'API key',
  },
]

export function getProvider(id) {
  return PROVIDERS.find(p => p.id === id) ?? PROVIDERS.find(p => p.id === 'custom')
}
